"""add programm func role

Revision ID: 08c73179e820
Revises: 821f34a6b18a
Create Date: 2024-12-26 13:18:18.884505

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = '08c73179e820'
down_revision = '821f34a6b18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('func_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('func_id', name=op.f('pk_functions'))
    )
    op.create_table('programm',
    sa.Column('programm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('programm_id', name=op.f('pk_programm'))
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_role'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('programm')
    op.drop_table('functions')
    # ### end Alembic commands ###
