"""add email

Revision ID: 109b1ea25a01
Revises: a0b6376267a7
Create Date: 2024-12-25 14:56:59.586688

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = '109b1ea25a01'
down_revision = 'a0b6376267a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'record_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('record_data', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'record_data')
    op.alter_column('records', 'record_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
