"""add UserAccess4

Revision ID: 3a27385bb1fb
Revises: fa7528517dc2
Create Date: 2024-12-26 14:11:24.734951

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = '3a27385bb1fb'
down_revision = 'fa7528517dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('user_access_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_access_user_id_users')),
    sa.PrimaryKeyConstraint('user_access_id', name=op.f('pk_user_access'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access')
    # ### end Alembic commands ###
