"""add UserAccess3

Revision ID: 6ef1f4b1ba94
Revises: c1e6edfff4d7
Create Date: 2024-12-26 14:03:50.099787

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = '6ef1f4b1ba94'
down_revision = 'c1e6edfff4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles'))
    )
    op.drop_table('role')
    op.add_column('user_access', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_user_access_user_id_users'), 'user_access', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_access_user_id_users'), 'user_access', type_='foreignkey')
    op.drop_column('user_access', 'user_id')
    op.create_table('role',
    sa.Column('role_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('role_id', name='pk_role')
    )
    op.drop_table('roles')
    # ### end Alembic commands ###
