"""add programm func role

Revision ID: 7f232d24e730
Revises: 109b1ea25a01
Create Date: 2024-12-26 13:16:25.985661

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = '7f232d24e730'
down_revision = '109b1ea25a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('huid', sa.String(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('users', 'huid')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
