"""add programm func role

Revision ID: 821f34a6b18a
Revises: 7f232d24e730
Create Date: 2024-12-26 13:17:21.818633

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = '821f34a6b18a'
down_revision = '7f232d24e730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
