"""add UserAccess2

Revision ID: c1e6edfff4d7
Revises: 08c73179e820
Create Date: 2024-12-26 13:42:53.394515

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = 'c1e6edfff4d7'
down_revision = '08c73179e820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('user_access_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('user_access_id', name=op.f('pk_user_access'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access')
    # ### end Alembic commands ###
