"""add access

Revision ID: c330afa21721
Revises: f72cbe7422dc
Create Date: 2024-12-26 14:15:21.915750

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = 'c330afa21721'
down_revision = 'f72cbe7422dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('access_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.Column('programm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['func_id'], ['functions.func_id'], name=op.f('fk_access_func_id_functions')),
    sa.ForeignKeyConstraint(['programm_id'], ['programm.programm_id'], name=op.f('fk_access_programm_id_programm')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_access_role_id_roles')),
    sa.PrimaryKeyConstraint('access_id', name=op.f('pk_access'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access')
    # ### end Alembic commands ###
