"""revision

Revision ID: ec46a4813637
Revises: 
Create Date: 2024-12-27 14:22:22.130052

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = 'ec46a4813637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('func_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('func_id', name=op.f('pk_functions'))
    )
    op.create_table('programm',
    sa.Column('programm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('programm_id', name=op.f('pk_programm'))
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records'))
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('huid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_table('access',
    sa.Column('access_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.Column('programm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['func_id'], ['functions.func_id'], name=op.f('fk_access_func_id_functions')),
    sa.ForeignKeyConstraint(['programm_id'], ['programm.programm_id'], name=op.f('fk_access_programm_id_programm')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_access_role_id_roles')),
    sa.PrimaryKeyConstraint('access_id', name=op.f('pk_access'))
    )
    op.create_table('user_access',
    sa.Column('user_access_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_access_user_id_users')),
    sa.PrimaryKeyConstraint('user_access_id', name=op.f('pk_user_access'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access')
    op.drop_table('access')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('records')
    op.drop_table('programm')
    op.drop_table('functions')
    # ### end Alembic commands ###
