"""add UserAccess5

Revision ID: f72cbe7422dc
Revises: 3a27385bb1fb
Create Date: 2024-12-26 14:12:07.559485

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = 'f72cbe7422dc'
down_revision = '3a27385bb1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
