"""add UserAccess4

Revision ID: fa7528517dc2
Revises: 6ef1f4b1ba94
Create Date: 2024-12-26 14:10:50.975318

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
from alembic import op
import sqlalchemy as sa


revision = 'fa7528517dc2'
down_revision = '6ef1f4b1ba94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('user_access_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_user_access_user_id_users'),
    sa.PrimaryKeyConstraint('user_access_id', name='pk_user_access')
    )
    # ### end Alembic commands ###
